FROM python:3.8

EXPOSE 8000

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONNONBUFFERED 1

ADD ./backend/requirements.txt .
RUN python -m pip install -r requirements.txt

WORKDIR /app
COPY ./backend .

RUN useradd appuser && chown -R appuser /app
USER appuser

CMD ["uvicorn", "main:app"]
